language: r
cache: packages
dist: trusty
os: linux

addons:
  apt:
    packages:
      - libpoppler-cpp-dev

r_github_packages:
  - jimhester/covr
  - ropensci/vcr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

r_check_args: "--as-cran"

jobs:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

notifications:
  email:
    on_success: change
    on_failure: change
